######################
# Common environment #
######################

import sys
import os
app_name = os.getcwd().split(os.sep)[-1]

if(os.path.isfile('NOT_SUPPORTED')):
    print('NOT_SUPPORTED file present. Aborting!')
    Exit(2)

MIR_ROOT = os.environ.get('MIR_ROOT')
if(MIR_ROOT == None):
    print('MIR_ROOT is not defined. Aborting!')
    Exit(2)

sys.path.append(MIR_ROOT + '/scripts')
import mir_utils

if os.path.isfile(MIR_ROOT+'/src/HAVE_PAPI'):
    PAPI_ROOT = os.environ.get('PAPI_ROOT')
    if(PAPI_ROOT == None):
        print('PAPI_ROOT is not defined. Aborting!')
        Exit(2)

# Don't use ICC since OpenMP support is only enabled for GCC.
compilers = ['gcc']
compiler = ''
for item in compilers:
    compiler = mir_utils.which(item)
    if(len(compiler) > 0):
        break;
if(len(compiler) == 0):
    print('Could not find a compiler. Aborting!')
    Exit(2)

env = Environment()
env['CC'] = [compiler[0]]
env['CCFLAGS'] = Split("""
-std=c99
-Wall
-Werror
-Wno-unused-function
-Wno-unused-variable
-Wno-unused-but-set-variable
-Wno-maybe-uninitialized
-fopenmp
-DLINUX
""")
env['CCFLAGS'] += ['-I' + MIR_ROOT+'/src']
env['LINKFLAGS'] = ['-pthread']
env['LIBS'] = Split("""
m
check
""")

env['LIBPATH'] = [MIR_ROOT + '/src']

if os.path.isfile(MIR_ROOT+'/src/HAVE_LIBNUMA'):
    env['LIBS'] += ['numa']
    env['CCFLAGS'] += ['-DMIR_MEM_POL_ENABLE']

if os.path.isfile(MIR_ROOT+'/src/HAVE_PAPI'):
    env['LIBS'] += ['papi']
    env['LIBPATH'] += [PAPI_ROOT + '/lib']

#####################
# Debug environment #
#####################

debug = env.Clone();
debug['CCFLAGS'] += Split("""
-O0
-g
-ggdb
-fdump-tree-optimized
-DALLOW_DEBUG_MESSAGES
""")
debug.Prepend(LIBS = ['mir-debug'])
debug.VariantDir('debug-build', '.', duplicate=0)
debug_src = debug.Glob('debug-build/*.c')
debug.Program(app_name +'-debug', source = debug_src)
Clean('.','debug-build')

###################
# Opt environment #
###################

opt = env.Clone();
opt['CCFLAGS'] += Split("""
-O3
-g
-fdump-tree-optimized
""")
opt.Prepend(LIBS = ['mir-opt'])
opt.VariantDir('opt-build', '.', duplicate=0)
opt_src = opt.Glob('opt-build/*.c')
opt.Program(app_name +'-opt', source = opt_src)
Clean('.','opt-build')

#######################
# Profile environment #
#######################

prof = env.Clone();
prof['CC'] = 'gcc'
prof['CCFLAGS'] += Split("""
-O1
-DNDEBUG
-fno-inline-functions
-fno-inline-functions-called-once
-fno-optimize-sibling-calls
-fno-omit-frame-pointer
-g
-fdump-tree-optimized
""")
prof.Prepend(LIBS = ['mir-opt'])
prof.VariantDir('prof-build', '.', duplicate=0)
prof_src = prof.Glob('prof-build/*.c')
prof.Program(app_name +'-prof', source = prof_src)
Clean('.','prof-build')

###############
# Test target #
###############

test = Command(target = 'test',
               source = './' + app_name + '-opt',
               action = [ './' + app_name + '-opt' + ' > test.result',
                          'cat test.result'])
AlwaysBuild(test)
