#!/bin/bash

APP=fft
TASKS=smp_ol_compute_w_coefficients_0_unpacked,smp_ol_compute_w_coefficients_1_unpacked,smp_ol_fft_39_unpacked,smp_ol_fft_aux_27_unpacked,smp_ol_fft_aux_28_unpacked,smp_ol_fft_aux_29_unpacked,smp_ol_fft_aux_30_unpacked,smp_ol_fft_aux_31_unpacked,smp_ol_fft_aux_32_unpacked,smp_ol_fft_aux_33_unpacked,smp_ol_fft_aux_34_unpacked,smp_ol_fft_aux_35_unpacked,smp_ol_fft_aux_36_unpacked,smp_ol_fft_aux_37_unpacked,smp_ol_fft_aux_38_unpacked,smp_ol_fft_twiddle_16_19_unpacked,smp_ol_fft_twiddle_16_20_unpacked,smp_ol_fft_twiddle_2_7_unpacked,smp_ol_fft_twiddle_2_8_unpacked,smp_ol_fft_twiddle_32_23_unpacked,smp_ol_fft_twiddle_32_24_unpacked,smp_ol_fft_twiddle_4_11_unpacked,smp_ol_fft_twiddle_4_12_unpacked,smp_ol_fft_twiddle_8_15_unpacked,smp_ol_fft_twiddle_8_16_unpacked,smp_ol_fft_twiddle_gen_4_unpacked,smp_ol_fft_twiddle_gen_5_unpacked,smp_ol_fft_twiddle_gen_6_unpacked,smp_ol_fft_unshuffle_16_21_unpacked,smp_ol_fft_unshuffle_16_22_unpacked,smp_ol_fft_unshuffle_2_10_unpacked,smp_ol_fft_unshuffle_2_9_unpacked,smp_ol_fft_unshuffle_32_25_unpacked,smp_ol_fft_unshuffle_32_26_unpacked,smp_ol_fft_unshuffle_4_13_unpacked,smp_ol_fft_unshuffle_4_14_unpacked,smp_ol_fft_unshuffle_8_17_unpacked,smp_ol_fft_unshuffle_8_18_unpacked,smp_ol_unshuffle_2_unpacked,smp_ol_unshuffle_3_unpacked
CALLED_FUNCS=compute_w_coefficients,factor,fft_aux,fft_base_16,fft_base_2,fft_base_32,fft_base_4,fft_base_8,fft_twiddle_16,fft_twiddle_2,fft_twiddle_32,fft_twiddle_4,fft_twiddle_8,fft_twiddle_gen,fft_twiddle_gen1,fft_unshuffle_16,fft_unshuffle_2,fft_unshuffle_32,fft_unshuffle_4,fft_unshuffle_8,unshuffle
INPUT=8388608
MIR_CONF="-w=1 -i -g -p"
OPF="5s"
PROCESS_TASK_GRAPH=1

# Profile and generate data
. ${MIR_ROOT}/scripts/task-graph/stub-profile.sh

