#!/bin/bash

APP=strassen
OUTLINE_FUNCTIONS=smp_ol_OptimizedStrassenMultiply_par_0_unpacked,smp_ol_OptimizedStrassenMultiply_par_1_unpacked,smp_ol_OptimizedStrassenMultiply_par_2_unpacked,smp_ol_OptimizedStrassenMultiply_par_3_unpacked,smp_ol_OptimizedStrassenMultiply_par_4_unpacked,smp_ol_OptimizedStrassenMultiply_par_5_unpacked,smp_ol_OptimizedStrassenMultiply_par_6_unpacked
CALLED_FUNCTIONS=matrixmul,FastNaiveMatrixMultiply,FastAdditiveNaiveMatrixMultiply,MultiplyByDivideAndConquer,OptimizedStrassenMultiply_par
INPUT="1024 32 10"
MIR_CONF="-w=1 -i -g -p"
OFILE_PREFIX="medium"
PROCESS_PROFILE_DATA=1

# Profile and generate data
. ${MIR_ROOT}/programs/common/stub-profile.sh

