import os
app_name = os.getcwd().split(os.sep)[-1]

######################
# Common environment #
######################

env = Environment()
env['CCFLAGS'] = Split("""
-std=c99
-Wall 
-Werror 
-Wno-unused-function 
-Wno-unused-variable
-Wno-unused-but-set-variable
-I/home/ananya/mir/src
-I/home/ananya/mir/test/common
""")
env['LINKFLAGS'] = ['']
env['LIBS'] = Split("""
pthread
numa
m
""")
env['LIBPATH'] = ['/home/ananya/mir/src/']

#####################
# Debug environment #
#####################

debug = env.Clone();
debug['CCFLAGS'] += Split("""
-O0
-g
-gdwarf-2
-DALLOW_DEBUG_MESSAGES
""")
debug['LIBS'] += ['mir-debug']
debug.VariantDir('debug-build', '.', duplicate=0)
debug_src = debug.Glob('debug-build/*.c')
debug.Program(app_name +'-debug', source = debug_src)

###################
# Opt environment #
###################

opt = env.Clone();
opt['CCFLAGS'] += Split("""
-O3
""")
opt['LIBS'] += ['mir-opt']
opt.VariantDir('opt-build', '.', duplicate=0)
opt_src = opt.Glob('opt-build/*.c')
opt.Program(app_name +'-opt', source = opt_src)

#######################
# Verbose environment #
#######################

verbose = env.Clone();
verbose['CCFLAGS'] += Split("""
-O3
-DALLOW_MESSAGES
-DCHECK_RESULT
""")
verbose['LIBS'] += ['mir-opt']
verbose.VariantDir('verbose-build', '.', duplicate=0)
verbose_src = verbose.Glob('verbose-build/*.c')
verbose.Program(app_name +'-verbose', source = verbose_src)
