#!/bin/bash

APP=strassen
OUTLINE_FUNCTIONS=smp_ol_OptimizedStrassenMultiply_par_0_unpacked,smp_ol_OptimizedStrassenMultiply_par_1_unpacked,smp_ol_OptimizedStrassenMultiply_par_2_unpacked,smp_ol_OptimizedStrassenMultiply_par_3_unpacked,smp_ol_OptimizedStrassenMultiply_par_4_unpacked,smp_ol_OptimizedStrassenMultiply_par_5_unpacked,smp_ol_OptimizedStrassenMultiply_par_6_unpacked
CALLED_FUNCTIONS=matrixmul,FastNaiveMatrixMultiply,FastAdditiveNaiveMatrixMultiply,MultiplyByDivideAndConquer,OptimizedStrassenMultiply_par
INPUT="8192 128 2000"
MIR_CONF="-w=1 -i -g -s=central-stack -p"
OFILE_PREFIX="10s"
PROCESS_PROFILE_DATA=1

# Profile and generate data
. ${MIR_ROOT}/programs/common/stub-profile.sh

