#!/bin/bash

intf=$1/mir_public_int.h
echo "Writing library interfaces to $intf"

echo "
/* DO NOT EDIT! THIS FILE IS AUTOGENERATED. */
#ifndef MIR_PUBLIC_INT_H
#define MIR_PUBLIC_INT_H

#include \"mir_types.h\"
" > $intf

find . -type f \( -name "*.h" ! -name "mir_public_int.h" \) -exec sed -n "/\/\*PUB_INT_INC_BEGIN\*\//,/\/\*PUB_INT_INC_END\*\//p" {} \; >> $intf
echo "
BEGIN_C_DECLS
" >> $intf
find . -type f \( -name "*.h" ! -name "mir_public_int.h" \) -exec sed -n "/\/\*PUB_INT_BASE_DECL_BEGIN\*\//,/\/\*PUB_INT_BASE_DECL_END\*\//p" {} \; >> $intf
find . -type f \( -name "*.h" ! -name "mir_public_int.h" \) -exec sed -n "/\/\*PUB_INT_DECL_BEGIN\*\//,/\/\*PUB_INT_DECL_END\*\//p" {} \; >> $intf
find . -type f \( -name "*.h" ! -name "mir_public_int.h" \) -exec sed -n "/\/\*PUB_INT_BEGIN\*\//,/\/\*PUB_INT_END\*\//p" {} \; >> $intf
find . -type f \( -name "*.h" ! -name "mir_public_int.h" \) -exec sed -n "/\/\*PUB_INT\*\//p" {} \; >> $intf
echo "
END_C_DECLS
" >> $intf

echo "
#endif
" >> $intf
