#!/bin/bash

intf=mir_lib_int.h
echo "Writing library interfaces to $intf"

echo "
/* DO NOT EDIT! THIS FILE IS AUTOGENERATED. */
#ifndef MIR_LIB_INT_H
#define MIR_LIB_INT_H

#include \"mir_types.h\"
#include \"mir_omp_int.h\"
" > $intf

find . -type f \( -name "*.h" ! -name "mir_lib_int.h" \) -exec sed -n "/\/\*LIBINT_INC_BEGIN\*\//,/\/\*LIBINT_INC_END\*\//p" {} \; >> $intf
echo "
BEGIN_C_DECLS 
" >> mir_lib_int.h
find . -type f \( -name "*.h" ! -name "mir_lib_int.h" \) -exec sed -n "/\/\*LIBINT_DECL_BEGIN\*\//,/\/\*LIBINT_DECL_END\*\//p" {} \; >> $intf
find . -type f \( -name "*.h" ! -name "mir_lib_int.h" \) -exec sed -n "/\/\*LIBINT_BEGIN\*\//,/\/\*LIBINT_END\*\//p" {} \; >> $intf
find . -type f \( -name "*.h" ! -name "mir_lib_int.h" \) -exec sed -n "/\/\*LIBINT\*\//p" {} \; >> $intf
echo "
END_C_DECLS 
" >> $intf

echo "
#endif
" >> $intf
