#ifndef MIR_DEFINES_H
#define MIR_DEFINES_H 1

// Workers
#define MIR_WORKER_MAX_COUNT 100
#define MIR_WORKER_STACK_SIZE_MULTIPLIER 10
#define MIR_WORKER_EXP_BOFF_RESET 1
#define MIR_WORKER_EXP_BOFF_SCALE 2
#define MIR_WORKER_EXP_BOFF_ROOF 128
#define MIR_WORKER_BACKOFF_DURING_SYNC 
#define MIR_WORKER_EXPLICIT_BIND 

// Task
//#define MIR_TASK_DEBUG 
#define MIR_TASK_DEFAULT_NAME "NO_NAME"
#define MIR_TASK_ID_START 0
#define MIR_TASKWAIT_ID_START 0
#define MIR_TASK_DATA_MAX_SIZE 256
// For Floorplan
//#define MIR_TASK_VARIABLE_DATA_SIZE
//DEPRECATED #define MIR_TASK_DATA_MAX_SIZE 768
//#define MIR_TASK_ALLOCATE_ON_STACK 
// For UC_Dehaze
//#define MIR_TASK_VARIABLE_DATA_SIZE

// Queue
//#define MIR_QUEUE_DEBUG 
#define MIR_QUEUE_MAX_CAPACITY 8192
//#define MIR_QUEUE_MAX_CAPACITY 65536

// Types
#define MIR_SHORT_NAME_LEN 32
#define MIR_LONG_NAME_LEN 256
#define MIR_SBUF_SIZE 64

// Utils
#define MIR_ERROR_STR "MIR_FATAL: "
#define MIR_DEBUG_STR "MIR_DBG: "
#define MIR_INFORM_STR "MIR_INFO: "

// Statistics
#define MIR_STATS_FILE_NAME "mir-stats"

// Task graph
#define MIR_TASK_GRAPH_FILE_NAME "mir-task-graph"
#define MIR_TGPID_SIZE 512

// Memory allocator
#define MIR_MEMORY_ALLOCATOR_DEBUG 
#define MIR_PAGE_ALIGNMENT 64

// Recorder
#define MIR_RECORDER_USE_HW_PERF_COUNTERS 
#define MIR_RECORDER_BUFFER_MAX_SIZE (1*1024*256)
#define MIR_RECORDER_STACK_MAX_SIZE MIR_RECORDER_BUFFER_MAX_SIZE
#define MIR_RECORDER_STATE_META_DATA_MAX_SIZE 32
#define MIR_RECORDER_EVENT_META_DATA_MAX_SIZE 32

// Scheduling policy
#define MIR_SCHED_POL_DEFAULT "central-stack"
#define MIR_SCHED_POL_CENTRAL_STACK_PROCESS_STACK_SIZE 128

// Dynamic inlining
#define MIR_INLINE_TASK_IF_QUEUE_FULL 
// Creation inline: 0 = never, 1 = always, >1 = inlined if num tasks waiting per worker exceeds
#define MIR_INLINE_TASK_DURING_CREATION 0

// Memory allocation policy
#define MIR_MEM_POL_CACHE_NODES 
#define MIR_MEM_POL_RESTRICT 
#define MIR_MEM_POL_FAULT_IN_PAGES 
//#define MIR_MEM_POL_LOCK_PAGES 
// TILEPro64 specifc
//#define MIR_PAGE_NO_LOCAL_CACHING 
//#define MIR_PAGE_NO_L1_CACHING
//#define MIR_PAGE_NO_L2_CACHING 

// Shared memory
#define MIR_SHM_SIZE 16
#define MIR_SHM_KEY 31415926
#define MIR_SHM_SIGREAD '*'

#endif
